application: apkuploader
version: 6
runtime: python
api_version: 1

handlers:
- url: /
  script: top.py
- url: /s/
  static_dir: static
- url: /c/.*
  script: main.py
  login: required
- url: .*
  script: download.py
